[package]
name = "jpointer"
version = "0.1.0"
edition = "2021"

[dependencies]
itoa = { version = "1", optional = true }
serde = { version = "1", optional = true }

[dev-dependencies]
serde_json = "1"

[features]
default = ["itoa", "serde"]
itoa = ["dep:itoa"]
serde = ["dep:serde"]

